name: Application Test and Release Workflow

on:
  push:
    branches:
      - master

jobs:

  docker_hub_release:
    env:
        DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
      - run: docker build . -t enricmartos/spottern-landing-page:latest
      - run: docker push enricmartos/spottern-landing-page:latest


  heroku_release:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1.0.0
      - run: |+
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
      - run: heroku git:remote -a $(basename ${{ github.repository}} )
      - run: git push heroku HEAD:refs/heads/master
